config/routes.rb
Minitwitter2::Application.routes.draw do

 

  root 'login#login'
  
  get "login" => 'login#login'
  get "logout" => 'login#logout'
  post "login" => 'login#auth'
  
  get "register" => 'users#new'
  
  

  resources :users
  
  get "follower_connections/:id" => 'follower_connections#new'
  get "users/:id" => 'users#show'
  get "home" => 'users#home', as: :home
  get "register" => 'login#register'
  get "tweets" => 'tweets#index'
  
  post "tweets" => 'tweets#create'
  

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :poster, class_name: "User", foreign_key: "user_id"
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = get_recent_tweets(10)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
	@tweet = Tweet.new(user_id: session[:user_id], body: params[:tweet_text])
	@tweet.save
	redirect_to home_url
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweet_display.html.erb
<table class="table table-striped"> 
<% tweets.each do |tweet| %>
<tr>
	<td><%= link_to(image_tag(tweet.poster.image_url, class: "img-thumbnail", height: "128", width: "128"), action: "show", controller: "users", id: tweet.poster.id)  %></td>
	<td><%= link_to(tweet.poster.name, action: "show", controller: "users", id: tweet.poster.id)  %> sez: "<%= tweet.body %>" at <%= tweet.created_at.strftime("%Y-%m-%d") %> </td>
</tr>
<% end %>
</table>

app/views/tweets/_tweet_display_text_only.html.erb
<table class="table table-striped"> 
<% tweets.each do |tweet| %>
<tr>
	<td>Someone sez: "<%= tweet.body %>" at <%= tweet.created_at.strftime("%Y-%m-%d") %> </td>
</tr>
<% end %>
</table>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<%= render partial: "navbar/navbar" %>
<div class="container">
<% if notice %>
<div class="alert alert-info" role="alert"><%= notice %></div>
<% end %>
<h1>Recent Tweets</h1>
<%= render partial: "tweets/tweet_display", locals: {tweets: @tweets} %>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>