config/routes.rb
Minitwitter2::Application.routes.draw do

 

  root 'login#login'
  
  get "login" => 'login#login'
  get "logout" => 'login#logout'
  post "login" => 'login#auth'
  
  get "register" => 'users#new'
  
  

  resources :users
  
  get "follower_connections/:id" => 'follower_connections#new'
  get "users/:id" => 'users#show'
  get "home" => 'users#home', as: :home
  get "register" => 'login#register'
  get "tweets" => 'tweets#index'
  
  post "tweets" => 'tweets#create'
  

  

end

app/models/follower_connection.rb
class FollowerConnection < ActiveRecord::Base
	belongs_to :follower, :class_name => :User
	belongs_to :followee, :class_name => :User
	validates_uniqueness_of :followee, :scope => [:follower]
end

app/controllers/follower_connections_controller.rb
class FollowerConnectionsController < ApplicationController
  before_action :set_follower_connection, only: [:show, :edit, :update, :destroy]

  # GET /follower_connections
  # GET /follower_connections.json
  def index
    @follower_connections = FollowerConnection.all
  end

  # GET /follower_connections/1
  # GET /follower_connections/1.json
  def show
  end

  # GET /follower_connections/new
  def new
	if(session[:user_id] == nil) 
		redirect_to login_url
	else 
		@follower = User.find(session[:user_id])
		@followee = User.find(params[:id])
		FollowerConnection.create(follower: @follower, followee: @followee)
		redirect_to(:back, notice: "You are now following #{@followee.name}!")
	end
  
    
  end

  # GET /follower_connections/1/edit
  def edit
  end

  # POST /follower_connections
  # POST /follower_connections.json
  def create
    @follower_connection = FollowerConnection.new(follower_connection_params)

    respond_to do |format|
      if @follower_connection.save
        format.html { redirect_to @follower_connection, notice: 'Follower connection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @follower_connection }
      else
        format.html { render action: 'new' }
        format.json { render json: @follower_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follower_connections/1
  # PATCH/PUT /follower_connections/1.json
  def update
    respond_to do |format|
      if @follower_connection.update(follower_connection_params)
        format.html { redirect_to @follower_connection, notice: 'Follower connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @follower_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follower_connections/1
  # DELETE /follower_connections/1.json
  def destroy
    @follower_connection.destroy
    respond_to do |format|
      format.html { redirect_to follower_connections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower_connection
      @follower_connection = FollowerConnection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follower_connection_params
      params.require(:follower_connection).permit(:follower_id, :followee_id)
    end
end

app/helpers/follower_connections_helper.rb
module FollowerConnectionsHelper
end

app/views/follower_connections/_form.html.erb
<%= form_for(@follower_connection) do |f| %>
  <% if @follower_connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower_connection.errors.count, "error") %> prohibited this follower_connection from being saved:</h2>

      <ul>
      <% @follower_connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followee_id %><br>
    <%= f.number_field :followee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follower_connections/edit.html.erb
<h1>Editing follower_connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower_connection %> |
<%= link_to 'Back', follower_connections_path %>

app/views/follower_connections/index.html.erb
<h1>Listing follower_connections</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followee</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @follower_connections.each do |follower_connection| %>
      <tr>
        <td><%= follower_connection.follower_id %></td>
        <td><%= follower_connection.followee_id %></td>
        <td><%= link_to 'Show', follower_connection %></td>
        <td><%= link_to 'Edit', edit_follower_connection_path(follower_connection) %></td>
        <td><%= link_to 'Destroy', follower_connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower connection', new_follower_connection_path %>

app/views/follower_connections/new.html.erb
<h1>New follower_connection</h1>

<%= render 'form' %>

<%= link_to 'Back', follower_connections_path %>

app/views/follower_connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @follower_connection.follower_id %>
</p>

<p>
  <strong>Followee:</strong>
  <%= @follower_connection.followee_id %>
</p>

<%= link_to 'Edit', edit_follower_connection_path(@follower_connection) %> |
<%= link_to 'Back', follower_connections_path %>